name: Sync File

on:
  schedule:
    - cron: '0 0 * * *'  # 每天零点执行一次
  workflow_dispatch:
    

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Define files to fetch
        run: |
          echo "files=(
            'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list /tmp/Microsoft.list'
            'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml /tmp/netflix.yaml'
            'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml /tmp/netflix-geoip.yaml'
            'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.yaml /tmp/paypal.yaml'
            'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.yaml /tmp/spotify.yaml'
          )" >> $GITHUB_ENV

      - name: Fetch files
        run: |
          for file in ${{ env.files }}; do
            url=$(echo $file | cut -d' ' -f1)
            local_path=$(echo $file | cut -d' ' -f2)
            echo "Fetching $url..."
            if curl -o "$local_path" -f "$url"; then
              echo "Successfully fetched $url"
            else
              echo "Failed to fetch $url. Skipping update."
              exit 1
            fi
          done

      - name: Save File and Commit and push changes
        run: |
          git config --local user.name limlll
          git add
          git commit -m "Update file from another repository"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}